### ISSUE TITLE
problem with model loading

### ISSUE THREAD

**Issue by SimpleNumber** [lhatsk/AlphaLink#13]
Hi AlphaLink developers!

I am trying to use AlphaLink. I've downloaded the model via your dropbox link and unpacked it with gunzip. So I start the prediction like this:
```
 python predict_with_crosslinks.py ./test/test/input.fasta ./test/test/restraints.txt --distograms --checkpoint_path ./alphalink/resources/finetuning_model_5_ptm_CACA_10A.pt --uniref90_database_path /resources/alphafold2/uniref90/uniref90.fasta --mgnify_database_path /resources/alphafold2/mgnify/mgy_clusters.fa --pdb70_database_path /resources/alphafold2/pdb70/ --uniclust30_database_path /resources/alphafold2/uniclust30/uniclust30_2018_08/
```

The traceback I've got:
```
  File "/users/user/alphalink/AlphaLink/predict_with_crosslinks.py", line 571, in <module>  main(args)
  File "/users/user/alphalink/AlphaLink/predict_with_crosslinks.py", line 376, in main model, output_directory = load_models_from_command_line(args, config)
  File "/users/user/alphalink/AlphaLink/predict_with_crosslinks.py", line 271, in load_models_from_command_line model.load_state_dict(sd)
  File "/software/f2021/software/pytorch/1.10.0-foss-2021a-cuda-11.3.1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AlphaFold:
        size mismatch for xl_embedder.linear.weight: copying a param with shape torch.Size([128, 1]) from checkpoint, the shape in current model is torch.Size([128, 128]).
```
Do you have any ideas about what went wrong?:)

Best regards,
Julia

**Comment by lhatsk** [comment]
Hi Julia,

You are using the distogram flag with the contact network. In case your restraints are just contacts, you should remove the --distogram flag or if you want to use the distogram network, you need to use the other network weights: finetuning_model_5_ptm_distogram.pt

**Comment by SimpleNumber** [comment]
Thank you for a promt response!

I've used an example that you have in read.me:
```
     python predict_with_crosslinks.py 7K3N_A.fasta restraints.csv --distograms --checkpoint_path resources/AlphaLink_params/finetuning_model_5_ptm_CACA_10A.pt --uniref90_database_path uniref90.fasta --mgnify_database_path mgy_clusters.fa --pdb70_database_path pdb70/pdb70 --uniclust30_database_path uniclust30_2018_08/uniclust30_2018_08
```

Here I have one more question: Is the restrains.csv file should be the one that ```preprocessing_distributions.py``` produces? If so, in this file there is no info about cross-linked amino acids anymore... 

In the article, you give a very nice example with T1064, can you please share the input file for this prediction? I am basically trying to repeat your results:)

Best,
Julia

**Comment by lhatsk** [comment]
No, it doesn't have to be produced by preprocessing_distributions.py, but it has to contain a distogram. contacts_to_distograms.py would also work or you generate one manually. All the input files only include residue positions. If you want to have residue-specific distograms you would need to combine multiple distograms.

Note that the T1064 example was done with the contact network. You can find the features and crosslinks for some predictions on modelarchive, e.g., this one should be very close in performance: https://modelarchive.org/doi/10.5452/ma-rap-alink-1259 The pickled feature file can be used with --features

**Comment by SimpleNumber** [comment]
Sorry, I didn't get how the input file should look like.  Could you pls give an example?

> Note that the T1064 example was done with the contact network. You can find the features and crosslinks for some predictions on modelarchive, e.g., this one should be very close in performance: https://modelarchive.org/doi/10.5452/ma-rap-alink-1259 The pickled feature file can be used with --features

this one I also didn't get this, sorry:(  There are no csv files at all. I am not so experienced in the field. Could you pls give a more detailed explanation?

Thank you in advance,
Julia

**Comment by SimpleNumber** [comment]
Hi there!

I am back to try to make AlphaLink work:)
Sorry for this lengthy discussion. And thank you for your help! However, it still doesn't work. 

Now, I use this histogram mode. So ```restraints.csv```  looks like a table with 130 columns:
128 163 0.05 0.05 0.05 0.05 ...
147 77 0.01 0.015 0.05 0.05 ...
147 41 0.04 0.1 0.05 0.052 ...

I use this command:
```
 python predict_with_crosslinks.py /users/julia/alphalink/test/test/input.fasta /users/julia/alphalink/test/test/restrains_distr.csv --distograms --checkpoint_path /users/julia/alphalink/resources/finetuning_model_5_ptm_distogram.pt --uniref90_database_path /resources/alphafold2/uniref90/uniref90.fasta --mgnify_database_path /resources/alphafold2/mgnify/mgy_clusters.fa --pdb70_database_path /resources/alphafold2/pdb70/ --uniclust30_database_path /resources/alphafold2/uniclust30/uniclust30_2018_08/
```
This command gives me the following traceback:
```
INFO:/users/julia/alphalink/AlphaLink/predict_with_crosslinks.py:Loaded OpenFold parameters at /users/julia/alphalink/resources/finetuning_model_5_ptm_distogram.pt...
INFO:/users/julia/alphalink/AlphaLink/predict_with_crosslinks.py:Using precomputed alignments for bsa1 at /users/julia/alphalink/AlphaLink/alignments...
INFO:/users/julia/alphalink/AlphaLink/predict_with_crosslinks.py:Loaded 3 restraints...
Killed
```
since there is no error, I am puzzled. Why is it killed? Do you have any ideas about what could go wrong?


Best regards,
Julia

**Comment by lhatsk** [comment]
Sorry, I have absolutely no idea. Never seen this before. Are you somehow resources constrained? Like running out of memory? Is this target very large? If you are able to share the data, I could run it locally to verify.

**Comment by SimpleNumber** [comment]
It is a dummy example that I am trying to make work. Under this [link](https://www.dropbox.com/scl/fo/08ha7cqqpjf1gh581fu4e/h?rlkey=vntigr0wq1zn8zyj8ar7cu86q&dl=0) the files that I've used. Let me know if you can't access the folder. 

Thank you for your help!
cheers,
J

**Comment by lhatsk** [comment]
Worked fine for me. Required 18G of GPU memory.

INFO:predict_with_crosslinks.py:Loaded OpenFold parameters at resources/AlphaLink_params/finetuning_model_5_ptm_distogram.pt...
INFO:predict_with_crosslinks.py:Loaded 3 restraints...
INFO:predict_with_crosslinks.py:Running inference for bsa1...
INFO:predict_with_crosslinks.py:Inference time: 498.2697855802253
INFO:predict_with_crosslinks.py:Output written to bsa1_model_5_ptm_crosslinks_unrelaxed.pdb...
INFO:predict_with_crosslinks.py:Relaxed output written to bsa1_model_5_ptm_crosslinks_relaxed.pdb...

[bsa1_model_5_ptm_crosslinks_relaxed.pdb.zip](https://github.com/lhatsk/AlphaLink/files/12406611/bsa1_model_5_ptm_crosslinks_relaxed.pdb.zip)

**Comment by lhatsk** [comment]
Do you run it locally or is it submitted to some compute nodes with, e.g., SLURM?

**Comment by audrizzle** [comment]
Hello AlphaLink developers, 

I am trying to use the T1064 data from ModelArchive to run AlphaLink migrate-to-openfold-1.0 with the following: 

`python predict_with_crosslinks.py practice_fasta practice/T1064_8_LEU_10A_CA.pt --features practice/T1064.pkl --checkpoint_path resources/AlphaLink_params/finetuning_model_5_ptm_distogram_1.0.pt --uniref90_database_path resources/uniref90 --mgnify_database_path resources/mgnify --pdb70_database_path resources/pdb70 --uniclust30_database_path resources/uniclust30_2018_08 &> foo9.txt
`

And the output indicates that I am "Missing key(s) in state_dict:" ([link to output](https://pastebin.com/Zg1ENQYa)). 

Also, as a separate issue, I'm unable to run the test.test_model unit test. I was able to run the analogous unit test in my openfold installation in a separate conda environment, but not in my AlphaLink with my AlphaLink environment:
`(openfold_venv) ak@gpudev1:~/software/AlphaLink$ scripts/run_unit_tests.sh -v tests.test_model
test_compare (tests.test_model.TestModel) ... skipped 'Requires AlphaFold'
test_dry_run (tests.test_model.TestModel) ... FAIL

======================================================================
FAIL: test_dry_run (tests.test_model.TestModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/wynton/home/wiita/akishi/software/AlphaLink/tests/test_model.py", line 91, in test_dry_run
    out = model(batch)
  File "/wynton/home/wiita/akishi/.conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/wynton/home/wiita/akishi/software/AlphaLink/openfold/model/model.py", line 520, in forward
    _recycle=(num_iters > 1)
  File "/wynton/home/wiita/akishi/software/AlphaLink/openfold/model/model.py", line 322, in iteration
    inplace_safe=inplace_safe,
  File "/wynton/home/wiita/akishi/software/AlphaLink/openfold/model/model.py", line 177, in embed_templates
    _mask_trans=self.config._mask_trans,
  File "/wynton/home/wiita/akishi/.conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/wynton/home/wiita/akishi/software/AlphaLink/openfold/model/template.py", line 389, in forward
    assert(not self.training)
AssertionError

----------------------------------------------------------------------
Ran 2 tests in 0.834s

FAILED (failures=1, skipped=1)

Test(s) failed. Make sure you've installed all Python dependencies.
`

Any help would be greatly appreciated! Thanks. 

Sincerely,
Audrey

**Comment by lhatsk** [comment]
Hi Audrey,

I can't find the part about "missing keys" in the output. The CUDA error points towards something else, although I don't know what. The migrate-to-openfold-1.0 hasn't been maintained, I would suggest switching to the main branch. 

I have never run the tests before. These are the original OpenFold tests. They were not updated for AlphaLink. The error indicates that some dependencies are missing. You will probably also run into issues since there are no crosslink inputs in the tests.

**Comment by audrizzle** [comment]
Hi @lhatsk, 

Thanks for the info! I migrated back to the main branch and got it to work nicely with CUDA 11.3. 

I had some trouble getting my conda environment set up properly, but I exported my working environment [here ](https://pastebin.com/fB1mDEUP)if that's helpful to anybody.

Super cool tool! Here's a snapshot of what I recapitulated from your deposited structures compared to the crystal structure: 

![Image](https://github.com/user-attachments/assets/ae946b11-f424-49c7-b0c6-57a76e2f3c57)
