### ISSUE TITLE
Alphalink install failed

### ISSUE THREAD

**Issue by jIskCoder** [lhatsk/AlphaLink#22]
I have been trying to install virtual env using [environment.yml](https://github.com/lhatsk/AlphaLink/blob/main/environment.yml)

And get the following error:

```
Collecting deepspeed==0.5.10 (from -r /vast/scratch/users/iskander.j/AlphaLink/condaenv.s_3tgy1b.requirements.txt (line 2))
  Using cached deepspeed-0.5.10.tar.gz (515 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/NVIDIA/dllogger.git /vast/scratch/users/iskander.j/tmp/pip-req-build-b5e98t7e
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/vast/scratch/users/iskander.j/tmp/pip-install-16f1fgl7/deepspeed_58e11f6d38c1437fb3136539611b056b/setup.py", line 27, in <module>
          import torch
        File "/home/users/allstaff/iskander.j/.local/lib/python3.7/site-packages/torch/__init__.py", line 217, in <module>
          _load_global_deps()
        File "/home/users/allstaff/iskander.j/.local/lib/python3.7/site-packages/torch/__init__.py", line 177, in _load_global_deps
          raise err
        File "/home/users/allstaff/iskander.j/.local/lib/python3.7/site-packages/torch/__init__.py", line 172, in _load_global_deps
          ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
        File "/stornext/System/data/apps/rc-tools/rc-tools-1.0/bin/tools/envs/alphalink/lib/python3.7/ctypes/__init__.py", line 364, in __init__
          self._handle = _dlopen(self._name, mode)
      OSError: /home/users/allstaff/iskander.j/.local/lib/python3.7/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
                                                                                                                           failed

CondaEnvException: Pip failed
```

When I installed OpenFold from the [OpenFold GitHub](https://github.com/aqlaboratory/openfold#installation-linux), I got errors due to deprecated simtk version.

**Comment by lhatsk** [comment]
Hi,

Sorry for the late response! I guess we should also update the environment.yml and not just refer to the OpenFold GitHub. What were the simtk errors? I only remember changes with the openmm 8.0. You could try to remove the dlloger line from environment.yml and try to install it separately.

**Comment by jIskCoder** [comment]
Unfortunately I didnt note the errors. but from memory, I had to change the import statement in the code but then keys in a dictionary were missing and comparing the openfold code in this repo with the latest openfold code I found that it was different.

**Comment by lhatsk** [comment]
Yeah, changing the imports is expected for the newer version. They changed the module structure simtk.openmm has to be changed to openmm. Curious to know what keys were missing in what dictionary. Did this error occur during relaxation?

**Comment by sherryliu987** [comment]
If you're struggling to install AlphaLink, feel free to try https://www.tamarind.bio/alphalink. It's a web interface to use bioinformatics tools like AlphaLink for free.
